{{- if .Values.gateway.enabled -}}
apiVersion: {{ .Values.gateway.apiVersion }}
kind: HTTPRoute
metadata:
  name: {{ include "whisper-relay-server.fullname" . }}
  labels:
    {{- include "whisper-relay-server.labels" . | nindent 4 }}
    {{- with .Values.gateway.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml .Values.gateway.parentRefs | nindent 4 }}
  {{- with .Values.gateway.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.gateway.pathPrefix | quote }}
      backendRefs:
        - name: {{ include "whisper-relay-server.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}

